vich_uploader:
    db_driver: orm
    mappings:
        film_images:
            uri_prefix: '%film_images%'
            upload_destination: '%kernel.project_dir%/public%film_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
